### ISSUE TITLE
Find polygon centroid

### ISSUE THREAD

**Issue by missinglink** [kpawlik/geojson#3]
Is there a easy way to find the center point of a geojson feature?

**Comment by jharlap** [comment]
Given the library seems to be purely about marshalling to GeoJSON, I suspect this is out of scope for this package. Furthermore, the question of how to compute the centroid of a polygon on a spheroid or ellipsoid is, unfortunately, not what I'd call "easy". If you're only dealing with relatively small polygons, such as might represent buildings, and you can guarantee that the polygons don't straddle either the international dateline or one of the poles, then you can take a very easy approach and pretend the polygon is actually planar. In that case, the following code (based on http://en.wikipedia.org/wiki/Centroid#Centroid_of_polygon) may help you:

```go
func area(poly geojson.Polygon) float64 {
	s := 0.0

	ring := poly.Coordinates[0]
	for i := 0; i < len(ring)-1; i++ {
		s += float64(ring[i][0]*ring[i+1][1] - ring[i+1][0]*ring[i][1])
	}

	return 0.5 * s
}

// Centroid calculates the centroid of the exterior ring of a polygon using
// the formula at http://en.wikipedia.org/wiki/Centroid#Centroid_of_polygon
// but be careful as this applies Euclidean principles to decidedly non-
// Euclidean geometry. In other words, it will fail miserably for polygons
// near the poles, polygons that straddle the dateline, and for large polygons
// where Euclidean approximations break down.
func Centroid(poly geojson.Polygon) geojson.Coordinate {
	c := geojson.Coordinate{0, 0}

	ring := poly.Coordinates[0]
	for i := 0; i < len(ring)-1; i++ {
		c[0] += (ring[i][0] + ring[i+1][0]) * (ring[i][0]*ring[i+1][1] - ring[i+1][0]*ring[i][1])
		c[1] += (ring[i][1] + ring[i+1][1]) * (ring[i][0]*ring[i+1][1] - ring[i+1][0]*ring[i][1])
	}

	a := area(poly)
	c[0] /= geojson.CoordType(a * 6)
	c[1] /= geojson.CoordType(a * 6)
	return c
}
```

If the limitations (poles, dateline, large polys) don't work for your application, then you may want to take a look at page 54 of http://www.jennessent.com/downloads/Graphics_Shapes_Online.pdf
